"""Data contracts for the summarizer input layer."""

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field
from pydantic.types import PositiveInt


class SelectorConfig(BaseModel):
    """Configuration for the selector component."""

    model_config = ConfigDict(extra="forbid")

    max_posts: int = Field(..., description="Max number of posts for LLM context")
    max_comments_per_post: int = Field(..., description="Max number of comments per post for LLM context")
    max_post_chars: PositiveInt = Field(..., description="Max number of characters allowed in post excerpt")
    max_comment_chars: PositiveInt = Field(..., description="Max number of characters allowed in comment excerpt")


class PostPayload(BaseModel):
    """Compact representation of a Reddit post passed to the summarizer."""

    model_config = ConfigDict(extra="forbid")

    post_id: str = Field(..., description="Reddit post ID")
    subreddit: str = Field(..., description="Source subreddit (e.g., diy)")
    title: str = Field(..., description="Cleaned Reddit post title")
    url: str = Field(..., description="Canonical Reddit permalink")
    body_excerpt: str = Field(..., description="Truncated body text shown to the LLM")
    top_comment_excerpts: list[str] = Field(
        default_factory=list,
        description="Truncated comment excerpts selected for this post",
    )
    post_karma: int = Field(..., description="Native Reddit score (upvotes - downvotes)")
    num_comments: int = Field(..., description="Number of comments accepted by the fetcher for this post")
    relevance_score: float = Field(..., description="Fetcher-assigned relevance score")
    matched_keywords: list[str] = Field(
        default_factory=list,
        description="Fetcher keyword matches used in scoring",
    )


class SummarizeRequest(BaseModel):
    """Input contract consumed by the summarizer/LLM layer."""

    model_config = ConfigDict(extra="forbid")

    query: str = Field(..., description="Original user question")
    plan_id: UUID = Field(..., description="Planner-generated ID for this fetch run")
    post_payloads: list[PostPayload] = Field(
        ...,
        description="Selected Reddit posts with trimmed content for the LLM context",
    )
    prompt_version: str = Field(..., description="Version identifier for the prompt template")
    max_posts: int = Field(..., description="Cap on posts included in this request")
    max_comments_per_post: int = Field(..., description="Cap on comment excerpts per post")
    max_post_chars: PositiveInt = Field(..., description="Max characters allocated to each post body excerpt")
    max_comment_chars: PositiveInt = Field(..., description="Max characters allocated to each comment excerpt")


class ReferenceLink(BaseModel):
    """Link back to a Reddit post or external resource cited in a summary."""

    model_config = ConfigDict(extra="forbid")

    label: str = Field(..., description="Human-friendly title for the reference link")
    url: str = Field(..., description="Canonical URL users can follow for details")
    subreddit: str | None = Field(
        default=None,
        description="Optional subreddit name where this reference originated",
    )
    post_id: str | None = Field(
        default=None,
        description="Optional Reddit post ID if the link refers to a fetched post",
    )


class SummarizeResult(BaseModel):
    """Structured response returned by the LLM summarizer."""

    model_config = ConfigDict(extra="forbid")

    searched_subreddits: list[str] = Field(
        default_factory=list,
        description="Communities consulted during the fetch/search process",
    )
    summary: str = Field(..., description="Primary narrative summary generated by the LLM")
    highlights: list[str] = Field(
        default_factory=list,
        description="Optional bulleted takeaways or action items",
    )
    reference_links: list[ReferenceLink] = Field(
        default_factory=list,
        description="References that cite the posts supporting each highlight",
    )


__all__ = ["SelectorConfig", "PostPayload", "SummarizeRequest", "ReferenceLink", "SummarizeResult"]
